// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type Folder struct {
	ID        uuid.UUID
	OwnerID   uuid.UUID
	ParentID  *uuid.UUID
	Nonce     []byte
	EncName   []byte
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt *time.Time
}

type Item struct {
	ID          uuid.UUID
	OwnerID     uuid.UUID
	FolderID    *uuid.UUID
	Type        string
	Nonce       []byte
	EncData     []byte
	EncOverview []byte
	CreatedAt   time.Time
	UpdatedAt   time.Time
	DeletedAt   *time.Time
}

type Key struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	FolderID    *uuid.UUID
	ItemID      *uuid.UUID
	EncKey      []byte
	Nonce       []byte
	AccessLevel string
	CreatedAt   time.Time
}
