// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateFolder(ctx context.Context, arg CreateFolderParams) (CreateFolderRow, error)
	CreateFolderKey(ctx context.Context, arg CreateFolderKeyParams) error
	CreateItem(ctx context.Context, arg CreateItemParams) (CreateItemRow, error)
	CreateItemKey(ctx context.Context, arg CreateItemKeyParams) error
	GetFolderItems(ctx context.Context, arg GetFolderItemsParams) ([]GetFolderItemsRow, error)
	GetItemData(ctx context.Context, arg GetItemDataParams) (GetItemDataRow, error)
	GetUserFolders(ctx context.Context, userID uuid.UUID) ([]GetUserFoldersRow, error)
	IsFolderOwner(ctx context.Context, arg IsFolderOwnerParams) (int32, error)
	IsItemOwner(ctx context.Context, arg IsItemOwnerParams) (int32, error)
	RevokeUserAccess(ctx context.Context, arg RevokeUserAccessParams) error
	SoftDeleteFolder(ctx context.Context, arg SoftDeleteFolderParams) (int64, error)
	SoftDeleteItem(ctx context.Context, arg SoftDeleteItemParams) (int64, error)
	UpdateItemBlob(ctx context.Context, arg UpdateItemBlobParams) error
}

var _ Querier = (*Queries)(nil)
